name: build

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Check formatting
        shell: bash
        run: |
          files="$(gofmt -l $(git ls-files '*.go'))"
          test -z "$files" || { echo "Unformatted files:"; echo "$files"; exit 1; }

      - run: go test ./...

      - run: go vet ./...

      - run: go build ./cmd/vpn-bypass
